# 서버 설정
server:
  port: 8080  # 애플리케이션 서버가 사용할 포트 번호
  servlet:
    context-path: /myapp  # 애플리케이션의 컨텍스트 경로 설정

# 데이터베이스 설정
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/app  # 데이터베이스 연결 URL
    username: root  # 데이터베이스 사용자 이름
    password: 1234  # 데이터베이스 비밀번호
  jpa:
    hibernate:
      ddl-auto: create  # Hibernate의 DDL 생성 모드를 create로 설정
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect  # Hibernate의 데이터베이스 방언 설정
