# 서버 설정
server:
  port: 8080  # 애플리케이션 서버가 사용할 포트 번호
  servlet:
    context-path: /  # 애플리케이션의 컨텍스트 경로 설정

# 데이터베이스 설정
spring:
  thymeleaf:
    prefix: classpath:/templates/ # Thymeleaf가 읽어들일 파일 경로
    suffix: .html  # Thymeleaf가 읽어들일 파일 확장자
    check-template-location: true  # 템플릿 파일의 존재 여부를 확인할지 여부
    mode: HTML  # HTML5의 HTML을 사용한다는 의미
    cache: false # 템플릿 파일의 변경 여부를 확인할지 여부
  mvc:
    path match:
      matching-strategy: ant_path_matcher
    hidden-method:
      filter:
        enabled: true
  datasource:
    url: jdbc:mysql://localhost:3306/spring_dev?serverTimezone=Asia/Seoul&sslMode=DISABLED&allowPublicKeyRetrieval=true
    username: root  # 데이터베이스 사용자 이름
    password: 12341234  # 데이터베이스 비밀번호
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update  # Hibernate의 DDL 생성 모드를 설정
    show-sql: true # Hibernate가 실행한 SQL을 출력
    properties:
      hibernate:
        format_sql: true # Hibernate가 실행한 SQL을 정렬해서 출력
        dialect: org.hibernate.dialect.MySQL8Dialect  # Hibernate의 데이터베이스 방언 설정

# 파라미터 로그
logging:
  level:
    org.hibernate.orm.jdbc.bind: trace